version: '3.8'

services:
  postgres-db-user:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - ftn_devops_network
    environment:
      POSTGRES_DB: devops_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devops123

  user-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-user:5432/devops_user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - ftn_devops_network
    depends_on:
      - postgres-db-user
      - zipkin
      - loki
      - grafana
    restart: on-failure

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - ftn_devops_network

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ftn_devops_network

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - ftn_devops_network

networks:
  ftn_devops_network:
    external: true

volumes:
  postgres-db-user:

