version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - ftn_devops_network
    environment:
      POSTGRES_DB: devops_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devops123

  user-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/devops_user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - ftn_devops_network
    depends_on:
      - postgres-db
    restart: on-failure

networks:
  ftn_devops_network:
    external: true

volumes:
  postgres-db:
