name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Extract version from build.gradle
        id: get_version
        run: |
          echo "VERSION=$(grep '^version' build.gradle | cut -d '=' -f2 | xargs)" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-user-service:$VERSION .
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-user-service:$VERSION